export const FETCH_COMMENTS_BY_ID_SUCCESS = 'FETCH_COMMENTS_BY_ID_SUCCESS'
export const FETCH_COMMENTS_BY_ID_FAILURE= 'FETCH_COMMENTS_BY_ID_FAILURE'

export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS'
