export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS'
export const COMMENT_VOTE_FAILURE = 'COMMENT_VOTE_FAILURE'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE'

export const FETCH_COMMENTS_BY_ID_SUCCESS = 'FETCH_COMMENTS_BY_ID_SUCCESS'
export const FETCH_COMMENTS_BY_ID_FAILURE= 'FETCH_COMMENTS_BY_ID_FAILURE'


