export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const VOTE_REQUEST = 'UP_VOTE_REQUEST'
export const VOTE_SUCCESS = 'UP_VOTE_SUCCESS'
export const VOTE_FAILURE = 'UP_VOTE_FAILURE'

export const DELETE_REQUEST = 'UP_DELETE_REQUEST'
export const DELETE_SUCCESS = 'UP_DELETE_SUCCESS'
export const DELETE_FAILURE = 'UP_DELETE_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'
