export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const VOTE_REQUEST = 'UP_VOTE_REQUEST'
export const VOTE_SUCCESS = 'UP_VOTE_SUCCESS'
export const VOTE_FAILURE = 'UP_VOTE_FAILURE'